# Generated by Django 5.0.3 on 2024-03-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_message_alter_skill_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
    ]
