# Generated by Django 5.0.3 on 2024-03-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_skill_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
